//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banner()
        {
            this.Deal = new HashSet<Deal>();
        }
    
        public int id { get; set; }
        public string hightway_name { get; set; }
        public int lenght { get; set; }
        public int price { get; set; }
        public string status { get; set; }
        public string Fiofield
        {
            get
            {
                return $"Наименование : {hightway_name}";
            }
        }
        public string Far
        {
            get
            {
                return $"Расстояние от Москвы: {lenght} км";
            }
        }
        public string Cost
        {
            get
            {
                return $"Стоимость : {price}";
            }
        }
        public string Status
        {
            get
            {
                return $"Статус : {status}";
            }
        }  //банер {banner.hightway_name} {banner.lenght}
        public string Fullname
        {
            get
            {
                return $"{hightway_name} {lenght}км";
            }
        }  

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
    }
}
