//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int id { get; set; }
        public int Banner_id { get; set; }
        public int Client_id { get; set; }
        public int Worker_id { get; set; }
        public int period { get; set; }
        public string status { get; set; }
        public int price
        {
            get
            {
                return Banner.price * period;
            } 
        }
        public string ITOGO
        {
            get
            {
                return $"Итого: {ITOG} руб.";
            }
        }
        public string ITOG
        {
            get
            {
                return $"{Banner.price * period}";
            }
        }
        public string BannerName
        {
            get
            {
                return $"Банер: {Banner.Fullname}";
            }
        }
        public string ClientName
        {
            get
            {
                return $"Клиент: {Client.FIO}";
            }
        }
        public string WorkerName
        {
            get
            {
                return $"Работник: {Client.FIO}";
            }
        }
        public string Status
        {
            get
            {
                return $"Статус: {status}";
            }
        }
        public string Period
        {
            get
            {
                return $"Период: {period} мес.";
            }
        }
        public virtual Banner Banner { get; set; }
        public virtual Client Client { get; set; }
        public virtual worker worker { get; set; }
    }
}