//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANer
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public worker()
        {
            this.Deal = new HashSet<Deal>();
        }
    
        public int id { get; set; }
        public string FIO { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public string Login
        {
            get
            {
                return $"Логин: {this.login}";
            }
        }
        public string Password
        {
            get
            {
                return $"Пароль: {this.password}";
            }
        }
        public string Rolename
        {
            get
            {
                /* using (var db = new PomogiteEntities())
                {
                    var role = db.clientroles.Find(this.role_id);
                    if (role != null)
                    {
                        return $"Роль: {role.description}";
                    }
                }*/

                return $"Должность: {Role.name}";
            }
        }
        public string Fiofield
        {
            get
            {
                return $"ФИО: {this.FIO}";
            }
        }//worker
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
        public virtual Role Role { get; set; }
    }
}
